### ISSUE TITLE
Alias or Addon Domains for V4

### ISSUE THREAD

**Issue by michacassola** [EasyEngine/feature-requests#23]
Please add the abbility to set or update the vhost domains with EE V4:

`ee site create example.com --alias example.net --alias example.org`
`ee site update example.com --alias example.de --alias example.tld`

Thanks!

Edits from @kirtangajjar:
The following command should add alias domains and get their SSL certs:
`ee site update example.com --alias example.de --alias example.tld --ssl=le`

**Comment by michacassola** [comment]
@kirtangajjar and @rahul286 
Please move another earlier post of this to the feature-request repo and mark this one as duplicate or move this one and close the other. We should then change the title of the post so it includes all terminology in this direction.

**Comment by mbtamuli** [comment]
@mrrobot47 I think these are the changes required.

1. EasyEngine database update. (information for the alias domains)
2. ```VIRTUAL_HOST=${VIRTUAL_HOST},${ALIAS_DOMAINS}```
VIRTUAL_HOST -> PRIMARY DOMAIN
ALIAS_DOMAINS -> Other domains

3. Site's nginx config(server_name)
4. Redis config(TBD and tested)

**Comment by mbtamuli** [comment]
@mrrobot47 Please take a look at this as @sagarnasit won't be able to continue for some time.

**Comment by kirtangajjar** [comment]
Proposal for syntax for alias domains:

1. Specify aliases while creating site.
```
ee site create <sitename> --ssl=le --alias='<alias domains>'
ee site create a.test --ssl=le --alias='b.test,*.b.test,c.test'
``` 

2. Add a new alias domain after the site has created.
```
ee site alias add <sitename> <list of alias domains>
ee site alias add a.test d.test *.d.test
``` 

3. List alias domains of a site 
```
ee site alias list <sitename>
ee site alias list a.test
```

4. Remove alias domain of a site 
```
ee site alias remove <sitename> <list of alias domains>
ee site alias remove a.test d.test *.d.test
```

In future, we can also update `site list` command to list the alias domains for the site. This would be useful to see all the domains pointed to the server which are handled by EE.
```
ee site list --aliases --format=text
```

**Comment by mrrobot47** [comment]
Uniformity in syntax is required. While creating site, `<alias domains>` is passed as _associative arguments_, whereas in `add` and `remove`, ` <alias domains>` is passed as _positional arguments_.

Also, looking at rest of the commands, `delete` is generally used in EasyEngine as sub-command name instead of `remove`. Keeping that will be more intuitive to a user.

**Comment by michacassola** [comment]
I would suggest not adding an extra subcommand to site but to use update instead as users are used to it already:

To add alias:
`ee site create example.com --ssl=le --alias=site1.com,*.site2.com`
`ee site update example.com --alias=site1.com,*.site2.com` (should work with multiple update arguments)

To delete alias:
`ee site update example.com --alias-del=site1.com,*.site2.com`

To list all alias:
`ee site info example.com` Where they will simply be in an extra slot in the output list.
`ee site info example.com --alias` Will print only the alias.

This way we will also keep all that associative/positional arguments stuff @mrrobot47 wrote about.

Please also don't forget the `--wpsubdom` site creation command compatibility of `--alias=...` There it will also be very important for the Multisite users.

**Comment by madbradj** [comment]
Any update on this issue?

**Comment by michacassola** [comment]
It's in their roadmap's to-do list https://github.com/orgs/EasyEngine/projects/4 and will be in the next bigger release.
My guess is that right now they are very busy with other things.

**Comment by puccaso** [comment]
> `ee site create example.com --alias example.net --alias example.org --wpsubdom --wpredis --le `
> Meaning a MU install is made with subdomains being the alias domains and they would also need to be included in the letsencrypt certificate.

We really need this!

**Comment by csaltos** [comment]
In the meantime (or if stuck using an old ee version) here is how I workaround it:

Follow the instructions at the custom nginx-proxy override configurations -> https://github.com/jwilder/nginx-proxy#custom-nginx-configuration

As a summary, simply create this file:

/opt/easyengine/services/nginx-proxy/vhost.d/site1.com

With the content:

server_name site1.com site2.com;

Then:

ee service restart nging-proxy

And you are good to go !! ;) :)

Your changes are going to persist any other restart or reload.

NOTE: the name of the vhost file should be the same as the ee site you want to override.

**Comment by UgooAgbams** [comment]
What's the status of this issue?
Has it been implemented or yet to be?


> As a summary, simply create this file:
> 
> /opt/easyengine/services/nginx-proxy/vhost.d/site1.com
> 
> With the content:
> 
> server_name site1.com site2.com;
> 
> Then:
> 
> ee service restart nging-proxy

Your idea worked, but does not give one ability to install letsencrypt on those added domains.

Any alternatives?

**Comment by baitasite** [comment]
Issue is dead?

**Comment by koljasagorski** [comment]
How can I create a alias now?

**Comment by kangarooo** [comment]
How to make WP multisite sertificate to work now?

**Comment by kirtangajjar** [comment]
Update on this issue: As you'll might've been aware, partial support for alias domains was added to in [v4.1 release](https://easyengine.io/blog/easyengine-v4-1-0-release/). However, it was just limited to `wpsubdom` site. 

This will be fixed soon with https://github.com/EasyEngine/site-command/pull/341. Hopefully by the next release, this feature will be implemented completely :crossed_fingers:

**Comment by kirtangajjar** [comment]
Thank you all for your feedback. Alias domains feature is now available for all the site types. This was one of the most requested 
 and awaited features of EE, and finally, we've brought it to a close. 

You'll be able to use it in alias domains in all site types from v4.1.2.
