### ISSUE TITLE
Nginx performance optimization

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#32]
Came across a nice article. Need to check if EE is doing it right. 

https://t37.net/nginx-optimization-understanding-sendfile-tcp_nodelay-and-tcp_nopush.html

By the way, if anyone has any other performance optimization ideas/articles, please share here.

**Comment by kirtangajjar** [comment]
Since we're already incorporating the performance optimizations in EasyEngine, and no new comments have been here in >5 years, I'm closing this issue.
