### ISSUE TITLE
example.com and www.example.com site are different

### ISSUE THREAD

**Issue by radhe** [EasyEngine/feature-requests#34]
Updated by @rahul286 

2 cases:

`ee site create example.com`        # www should redirect to non-wwww

`ee site create www.example.com`        # non-www should redirect to wwww
#### New `-www` flag:

Possible values
- -www=auto
- -www=off

---

If example.com already exist then www.example.com should be allowed to create.

`^_^[root@example.com:/var/www]# ee site create www.example.com --html 
too many values to unpack (expected 2)
O_O[root@example.com:/var/www]#`

**Comment by kirtangajjar** [comment]
> ee site create example.com # www should redirect to non-wwww
> ee site create www.example.com # non-www should redirect to wwww

The behaviour mentioned in the issue description is excatly how it works in v4. The issue has been fixed.
