### ISSUE TITLE
Migrate Command

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#43]
http://community.rtcamp.com/t/best-migration-system-for-moving-a-site-to-ee-site/2078/

We already have internal scripts which we need to port to EE

2 cases need to be handled:
1. One EE server to another EE server
2. Non EE server to EE server

**Comment by kirtangajjar** [comment]
@rahul286 EE to EE Migration will simply be `ee site clone` + `ee site delete` as far as I can see. Is there anything else to it? 

Also Non-EE to EE seems too much hassle. There are cpanel sites, site on apache etc... LMK your thoughts on it. As per my current line of thought, it seems better to close this issue as ee site clone will do most of the job for us.

**Comment by rahul286** [comment]
Yep. If ee clone can handle cross-server then that's enough

**Comment by rahul286** [comment]
> Non EE server to EE server

☝️ We will be ignoring this
