### ISSUE TITLE
HTTPS Leaking like crazy

### ISSUE THREAD

**Issue by jacobmmp** [EasyEngine/feature-requests#49]
The issue is the way you implementet https with letsencrypt, you forgot to ad a default_server for the https, so right now if you only got one https site every vhost you got on the server called true https will end up pointing on the one site that got https enabled.

This is actually inflicting harm on SEO since they popup on google search results, please fix this azap, this is a major concerne to be honest.

**Comment by kirtangajjar** [comment]
This is no longer a feature request. It's a bug which is now being tracked at - https://github.com/EasyEngine/easyengine/issues/1488
