### ISSUE TITLE
Add php 7.3 support

### ISSUE THREAD

**Issue by PatelUtkarsh** [EasyEngine/feature-requests#63]
Add support PHP 7.3 as it's officially available. 

https://twitter.com/official_php/status/1070753276939960320

This can be optional support like ee3.

**Comment by mrrobot47** [comment]
`PHP 7.3.0` support will be added very soon. Once it is added, @rahul286 @PatelUtkarsh @rahulsprajapati what should be the default PHP version when a site is created using EasyEngine?

Currently, EasyEngine creates a site uses `PHP 7.2.12` if no specific `--php=<version>` flag is passed. What should be the default behaviour now that the current stable PHP version is `7.3.0`?

1. Continue creating sites with `PHP 7.2.12` by default?
1. Update to last stable of `7.2` family, i.e., `PHP 7.2.13` and use it as default?
1. Switch to the current stable `PHP 7.3.0` as the default PHP version as well as update `--php=7.2` to latest `7.2.13`?

Note: The supported PHP versions during installations will soon be populated to all the versions listed [here](https://github.com/EasyEngine/site-command/issues/116#issuecomment-444378463) under section `PHP version update for Site type PHP and WP`.

**Comment by PatelUtkarsh** [comment]
I would prefer point 2. We can use 7.3 as default after few releases. @mrrobot47

**Comment by rahulsprajapati** [comment]
Yep, keep the default php version to 7.2 and add support of other php7 versions to `--php` flag. As @PatelUtkarsh said we can update the default after few releases.

**Comment by gijo-varghese** [comment]
Any updates on this?

**Comment by kirtangajjar** [comment]
Support for php 7.3 has been added.
