### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/feature-requests#69]
https://github.com/roots/bedrock

It supports composer and follows https://12factor.net/

If added to EasyEngine, it can work similar to [VIP style](https://easyengine.io/handbook/wordpress-vip/). 

```
# new project 
ee site create example.com --bedrock

# start with existing git repo
ee site create example.com --bedrock=git@github.com:rtcamp/my-bedrock-site.git
```

If anyone has used bedrock before, how is your experience thus far? Any feedback will help us decide better.

**Comment by kirtangajjar** [comment]
@rahul286 We haven't faced the need to use bedrock in a while. Are you still considering to add support for it in EE?

**Comment by rahul286** [comment]
No. Many things changed since then. We are unlikely to use bedrock in the future.
