### ISSUE TITLE
Mautic Tracking and Email Marketing

### ISSUE THREAD

**Issue by michacassola** [EasyEngine/feature-requests#78]
Please add Mautic as a hosting option.
https://www.mautic.org/
https://wordpress.org/plugins/wp-mautic/

`ee site create mautic.example.com --type=mautic`

They also use composer so automated installation might be similar to wordpress?
The benefit would be that EasyEngine becomes more useful and used as a wordpress hosting platform.

For now I will have to manually install mautic on a php/mysql site.
`ee site create example.com --type=php --with-db`

**Comment by petebytes** [comment]
I am using easyengine for mautic as well :) this would be a cool feature.
If someone can give me some guidance, I can try implementing it.

**Comment by michacassola** [comment]
Dear @petebytes 

that sounds great! Unfortunately my coding skills are not existant yet so I'll try to give infos to you on where to find what.

The general docu is here: https://easyengine.io/handbook/developer/custom-command
You can see under https://easyengine.io/handbook/developer/custom-command#creating-your-own-site-types how to create another site type.

It says to use the php-type template as a starting point:
https://github.com/EasyEngine/site-type-php/
https://github.com/EasyEngine/site-type-php/blob/develop/src/PHP.php

Hope this helped.

**Comment by michacassola** [comment]
Hey @petebytes, did you find time to take a look yet?
And more importantly, if I manually install it, I still don't feel safe as I don't know how to write a backup script for it. Any hint's on that would be very very welcome!

**Comment by petebytes** [comment]
@michacassola I have not - on the verge of releasing my first bootstraped product :)

Regarding backups, checkout this repo https://github.com/microram/ee4-tools
If you have sites that use local db, then take a look at my pull request
https://github.com/microram/ee4-tools/pulls

**Comment by michacassola** [comment]
Thank you very much!
Unfortunately I dont use AWS, I need backups to Google Drive.

Dear @microram, would you be so kind and make a script that backups to Google Drive with rclone?
Would it work with Mautic?
Maybe this could also be useful for https://github.com/EasyEngine/feature-requests/issues/19 ?

**Comment by microram** [comment]
Thanks @petebytes I have merged your changes. 
@michacassola  Adding rclone for backup should be as easy as changing the 'aws s3 cp' lines to 'rclone copy' and adjusting s3: to your rclone folder as needed. Please clone a copy and give it a try. Post a fork if you get it working.

**Comment by kirtangajjar** [comment]
Hey @michacassola,  we are going to add support for [custom docker-compose](https://github.com/EasyEngine/easyengine/pull/1462) in next version of easyengine. This will enable users to override docker-compose configuration such that it won't get overwritten on EE upgrades. That will make adding new sites types quiet easy. 

So will be able to create a php site with database and then create a `docker-compose-custom.yml` in which you will be able to replace php image with mautic image and it will work. 

So I'm closing this issue for now. After new release if you still have any issues, feel free to comment on this issue.
