### ISSUE TITLE
Expose database to external network

### ISSUE THREAD

**Issue by eliasjnior** [EasyEngine/feature-requests#80]
I didn't find any way or any documentation how to expose the database. I know that's not the best security, but I think should be available how to expose to external network.

**Comment by michacassola** [comment]
@eliasjnior What is your usecase anyway? Maybe a different kind of feature request is required like running EE in a cloud where the DB container sits on one node and the rest on others...?

**Comment by eliasjnior** [comment]
@michacassola I needed that because actually my client programmer needed to integrate their ERP, and they connect to database. So, as I couldn't find any solution, I just created a new container with MariaDB and changed the site settings to that database. It's working, no problems, but I would like to have it "in correct way".

**Comment by michacassola** [comment]
Maybe the API could serve as a way to get and post data to the wordpress DB through wordpress? https://developer.wordpress.org/rest-api/
https://stackoverflow.com/questions/46249779/how-to-access-to-wordpress-database-from-a-mobile-app

**Comment by eliasjnior** [comment]
@michacassola that was my recommendation for my client. But for some reason he said could work only with database, the API wouldn't fit in his case (I think he don't know how to use). For now I will keep using a separate Docker only for database. Maybe I can think in something after :P
