### ISSUE TITLE
Custom site docker-compose for greater customisation

### ISSUE THREAD

**Issue by dhsathiya** [EasyEngine/feature-requests#87]
Eg. files:
```
$ ls -al
...
docker-compose.yml 
docker-compose.php.yml
docker-compose.nginx.yml
docker-compose-admin.yml
...
```
Currently admin-tools works in the similar way with the following command
```
docker-compose -f docker-compose.yml -f docker-compose-admin.yml up -d nginx 
```
providing some extension to the same will give extra features such as mounting extra volumes, parameters etc.

**Comment by dhsathiya** [comment]
Draft PR: https://github.com/EasyEngine/easyengine/pull/1462

**Comment by mrrobot47** [comment]
Completed in https://github.com/EasyEngine/easyengine/pull/1462
